$( function() {
  var availableTags = [
"typer",
"funktioner",
"datastrukturer",
"listor",
"tupler",
"användardefinierade typer",
"top-down programdesign",
"rekursion",
"rekursiva typer",
"tidskomplexitet",
"input-output",
"moduler",
"abstraktion",
"verifiering",
"högre ordningens funktioner",
"data-centrisk programmering",
"logik",
"mängdlära",
"relationer",
"bevis",
"motsägelsebevis",
"heltalsaritmetik",
"kombinatorik",
"grafteori",
"boolesk algebra",
"kombinatoriska nät",
"sekvensnät",
"alu",
"dataväg",
"styrenhet",
"minne",
"in- och ut- enheter",
"instruktionsuppsättning",
"maskinspråk",
"assembler",
"digitalteknik",
"matriser",
"vektorer",
"linjära avbildningar",
"ekvationssystem",
"egenvektorer",
"egenvärden",
"baser",
"dimensioner",
"relationsmatriser",
"matlab",
"objektorienterad",
"objekt",
"klass",
"datainkapsling",
"konstruktorer",
"metoder",
"instansvariabler",
"klassvariabler",
"standardbibliotek",
"kodningsstandard",
"namnsättning",
"kommentering",
"derivata",
"intergral",
"linjärisering",
"optimalitetskriterier",
"polynom",
"potensserier",
"envariabelanalys",
"kretskoppling",
"paketkoppling",
"datornätverk",
"distribuerad",
"applikationsprotokoll",
"www",
"dns",
"sockets",
"datagram",
"dataöverföring",
"tcp",
"udp",
"stockningskontroll",
"internet",
"protokoll",
"adressering",
"ipv4",
"ipv6",
"arp",
"icmp",
"dv",
"ls",
"autonoma system",
"rip",
"ospf",
"bgp",
"lan",
"mac",
"ethernet",
"switching",
"vlan",
"trådlös",
"brandvägg",
"paket",
"wlan",
"c",
"test",
"systemprogrammering",
"händelser",
"avbrott",
"räknarkretsar",
"seriekommunikation",
"tidsdelningssystem",
"periferikretsar",
"mikrodatorsystem",
"mikroprocessor",
"periferienheter",
"projektarbete",
"versionshantering",
"rapport",
"dokumentation",
"sannolikhetslära",
"markovkedjor",
"stokastisk",
"väntevärde",
"varians",
"korrelation",
"stora talens lag",
"centrala gränsvärdessatsen",
"statistik",
"skattningar",
"konfidensintervall",
"kombinationer",
"permutationer",
"modeller",
"abstrakta datatyper",
"komplexitetsanalys",
"träd",
"fält",
"hashtabeller",
"köer",
"prioritetsköer",
"lexika",
"grafer",
"iteratorer",
"sortering",
"mekanik",
"newton",
"rörelser",
"komponenterna",
"partiklar",
"värmelära",
"termodynamik",
"processer",
"vågfysik",
"vågor",
"interferens",
"diffraktion",
"arbete",
"energi",
"rotationsrörelse",
"rörelsemängd",
"rörelsemängdsmoment",
"oscillationer",
"superposition",
"differentialekvationer",
"transienta förlopp",
"asic",
"fpga",
"vhdl",
"digitala kretsar",
"hårdvarukonstruktion",
"processor",
"tillståndsmaskin",
"dsl",
"domänspecifikt språk",
"funktionell programmering",
"programkalkyl",
"kategoriteori",
"medelvärdessatser",
"taylors formel",
"haskell",
"laplace",
"transformer",
"parallellism",
"synkronisering",
"kritiska regioner",
"ömsesidig uteslutning",
"deadlock",
"livelock",
"busy waiting",
"semaforer",
"monitorer",
"rendezvous",
"erlang",
"linda",
"resource allocation",
"dining philosophers",
"pipelining",
"minneshierarki",
"cacheminnen",
"huvudminne",
"virtuellt minne",
"fler-kärniga",
"kretselement",
"ohm",
"kirchhoff",
"effekt",
"elektriska nät",
"växelström",
"frekvensegenskaper",
"bodediagram",
"operationsförstärkare",
"elektromagnetism",
"likström",
"ström",
"spänning",
"absolut summer",
"energisignaler",
"bandbegränsade signaler",
"linjäritet",
"skift-invarians",
"kausalitet",
"bibo",
"fourierserier",
"fourier",
"z-transform",
"fouriertransform",
"lti",
"lti-ekvationen",
"nyquist-frekvensen",
"samplingsteoremet",
"dft",
"sampling",
"lti-system",
"signalmodeller",
"parseval",
"impulssvar",
"stegsvar",
"överföringsfunktion",
"frekvenssvar",
"maxwell-boltzmanns fördelningsfunktion",
"fasta tillstånd",
"kristallstruktur",
"röntgen",
"elektrondiffraktion",
"fermi-diracs fördelningsfunktion",
"tillståndstätheter",
"frielektronmodellen",
"elektronstruktur",
"fotoelektronspektra",
"brillouinzoner",
"konduktivitet",
"isolatorer",
"halvledare",
"roman",
"novell",
"pjäs",
"poesi",
"texter",
"kreativt skrivande",
"litteraturteori",
"narratologi",
"läsarstrategier",
"skönlitteratur",
"tolkning",
"människa-teknologi-samhälle",
"mts",
"algoritm",
"o-notation",
"ordo",
"grafalgoritmer",
"giriga algoritmer",
"divide-and-conquer",
"dynamisk programmering",
"backtracking",
"implicita sökträd",
"branch-and-bound",
"komplexitetsteori",
"approximationsalgoritmer",
"p",
"np",
"npc",
"rummet",
"gränsvärden",
"kontinuitet",
"differentierbarhet",
"kedjeregeln",
"partiella derivator",
"gradient",
"tangentplan",
"differentialer",
"funktionalmatriser",
"funktionaldeterminanter",
"trippelintegraler",
"variabelsubstitution",
"polärakoordinater",
"sfäriska koordinater",
"arean av buktig yta",
"greens formel",
"kurvintegraler",
"normalytintegraler",
"stokes satser",
"vågekvationen",
"hållbara energisystem",
"ekologi",
"växthuseffekten",
"reglerproblem",
"återkoppling",
"framkoppling",
"servofunktioner",
"parametervariationer",
"överföringsfunktioner",
"transient- och frekvensanalys",
"filter",
"pi- och pid-regulatorer",
"kaskadreglering",
"monader",
"domänspecifika programbibliotek",
"pretty printing",
"syntax",
"semantik",
"funktorer",
"monadtransformerare",
"resistorer",
"kondensatorer",
"induktorer",
"transistorer",
"effektsteg",
"mönsterkort",
"databas",
"sql",
"jdbc",
"xml",
"grafiskt gränssnitt",
"html",
"css",
"javascript",
"ajax",
"java servlet api",
"java server faces"

  ];
  $("#tags").autocomplete({
    source: availableTags,
	minLength: 2  
  });
} );